# -*- coding: utf-8 -*-
"""variable

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oWEHFxbTPVxib85nYX_efzFN07realUO

**variable** is also known as an identifier and used to hold certain value.
variable names can be a group of both the letters and digits ,but they have to begain with a letter or an undersore.
1.the first character of the variable must be an alphabet or underscore(_).
2.expect the first charactor remaining can be an alphabet of lower -case(a-z) upper case (A_Z) underscore or digit .
3.identifier names are case senstive,for example.myVarible,and myvariable are not the same .
4.identifier name must not contain any defined keywords white space or speacial character(*,@,!,#,^,&,%).
"""

a123 = 100

"""variable is also known as an identifier and useful to hold certain value."""

print(a123)

_mynum=6

print(_mynum)

student='deepak'
subject ='math'
age =15
marks=45.5

print(student)
print(subject)
print(age)
print(marks)

"""Data Type In Python"""

StudentMarks=40
StudentAge =18
name_of_students='Run'

print(name_of_students,StudentAge,StudentMarks)